### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by azizsayfiddin** [gXLg/jutsu-api#1]
<img width="1374" alt="Screenshot 2023-01-09 at 15 48 15" src="https://user-images.githubusercontent.com/114720383/211291015-6439b904-111b-4770-bd97-f7c8fd1fb228.png">
How to run?

**Comment by gXLg** [comment]
Dang it! I was redoing inner structure and forgot about that one

**Comment by gXLg** [comment]
Fixed in [commit](https://github.com/gXLg/jutsu-api/commit/5c6f8f3b111e41a3e304e7a6a85a66605ec50ae9)
