### ISSUE TITLE
How Can I download anime series from 120-1046 for example?

### ISSUE THREAD

**Issue by azizsayfiddin** [gXLg/jutsu-api#2]

**Comment by gXLg** [comment]
Can be easily done, iterate over seasons and in each until you reach first index, then add all to a list until needed index, then download then.

Untested code, but general idea:
```py
import Jutsu
from multiprocessing.pool import ThreadPool

# <getting anime here>

first = 120
last = 1046

i = 0
episodes = []
for s in anime.content.seasons:
  for e in s.episodes:
    i += 1
    if i >= first:
      episodes.append(e)
    if i == last:
      break

def downloader(e, i):
  e.download(local = f"Episode {i}")

# here threads count
pool = ThreadPool(3)
pool.map(downloader, zip(episodes, range(first, last + 1)))
```

**Comment by gXLg** [comment]
I will add new API functions for this purpose later on

**Comment by azizsayfiddin** [comment]
<img width="1099" alt="Screenshot 2023-01-09 at 17 41 26" src="https://user-images.githubusercontent.com/114720383/211310465-606239a5-8c7f-4ee9-9f14-67f6a9905e10.png">
IndexError
<img width="1270" alt="Screenshot 2023-01-09 at 17 42 32" src="https://user-images.githubusercontent.com/114720383/211310582-a09a5545-dd91-4251-8c76-b6ccb374e306.png">

**Comment by gXLg** [comment]
I hate, how `jut.su` is so inconsistent about their html generation. Fixed in the newest commit

**Comment by aljustiet** [comment]
https://user-images.githubusercontent.com/114720383/211313975-384b8358-724c-4aa0-9755-d294df5b5f01.mp4

**Comment by azizsayfiddin** [comment]
https://user-images.githubusercontent.com/114720383/211314116-70322924-f124-463d-8256-867e4d51edb0.mp4

**Comment by gXLg** [comment]
Make print debug for the `episodes` list

**Comment by gXLg** [comment]
Also, I can't just help you debug your code here. Please contact me on discord (sas24#9133)

**Comment by azizsayfiddin** [comment]
https://user-images.githubusercontent.com/114720383/211316297-8087a0c7-be4b-49db-bc55-6aa2a379f3f8.mov

**Comment by gXLg** [comment]
Fixed in the lastest commit,

read the new Documentation for new functionality
