### ISSUE TITLE
Спасибо

### ISSUE THREAD

**Issue by Shortkort** [gXLg/jutsu-api#3]
ХЗ увидишь ты это или нет, спасибо за апишку. Пришлось немного перелопатить чтобы делала то что мне надо, ты мой спаситель)

**Comment by gXLg** [comment]
Здравствуйте, спасибо за отзыв. Что вам пришлось изменить в АПИ для более комфортного использования?

**Comment by Shortkort** [comment]
Мне нужно было скачивать не все серии подряд, а те которые я задам в нужном диапазоне

**Comment by gXLg** [comment]
Это можно сделать без проблем, просто введите индексы нужных серий в списке, например `anime.selector.select_episodes(items = [0, 1, 4, 6])`, чтобы скачать первую, вторую, затем пятую и седьмую серию

**Comment by Shortkort** [comment]
Спасибо, не разобрался видимо в коде(
А есть ли возможность скачивать видео с обрезанным опенингом и эндингом?

**Comment by gXLg** [comment]
Нет, такой функции нету. Однако в АПИ присутствует информация о временах опенинга и эндинга, так что можно самому обрезать видео после скачивания, например с помощью модуля `moviepy` или с `ffmpeg`
