### ISSUE TITLE
how to get anime id? (как получить айди аниме?)

### ISSUE THREAD

**Issue by hinqiwame** [gXLg/jutsu-api#4]
было бы круто если тупо 
```python
def show_episodes(api, anime):
    # список серий в сезоне
    episodes = api.anime(anime.id).content.seasons
    for i, season in enumerate(episodes):
        print(f"Season {i + 1}: {season.title}")
        for j, episode in enumerate(season.episodes):
            print(f"  Episode {j + 1}: {episode.title}")
    return episodes
```

**Comment by hinqiwame** [comment]
или как можно получить прямую ссылку на mp4?

**Comment by gXLg** [comment]
Чтобы получить айди аниме, нужно использовать поиск, для этого смотрите отдел документации `API.search()`.

Чтобы выбрать все эпизоды аниме, как у Вас показано в функции, достаточно сделать `anime.selector.select_episodes()`, это вернёт объект `Downloader` со списком всех эпизодов. Подробнее в документации под `Selector`. Чтобы получить количество всех эпизодов, достаточно использовать `anime.content.count`.

Ссылка на mp4-видео файл имеет хэш, который зависит от `User-Agent`, поэтому ссылка, полученная через API, не будет работать в браузере и наоборот. Чтобы, несмотря на это, получить прямую ссылку на файл, необходимо выбрать нужный элемент из списка объекта `dowloader.items`, например вот так:
```py
episode_1_player = downloader.items[0][0] # возращает объект Player
link = episode_1_player.link
```

Надеюсь, я смог Вам помочь.
