### ISSUE TITLE
Как работает эта апишка?

### ISSUE THREAD

**Issue by redplcs** [gXLg/jutsu-api#6]
У сайта же нет своего апи

**Comment by NoPlagiarism** [comment]
Путём парсинга страниц, получения с них данных и упаковывания данных в красивую обёртку

Для подробностей всегда можно прочитать исходный код

**Comment by azizsayfiddin** [comment]
На универсальном python.

**Comment by gXLg** [comment]
Да, люди правильно написали - парсится сам сайт `jut.su` с надеждой, что формат сайта более менее устойчивый... Что к сожалению не всегда работает...

**Comment by redplcs** [comment]
> Путём парсинга страниц, получения с них данных и упаковывания данных в красивую обёртку
> 
> Для подробностей всегда можно прочитать исходный код

Я не питонист и лесть во все это, когда можно просто спросить, не собираюсь. За ответы спасибо

**Comment by NoPlagiarism** [comment]
> Я не питонист

Это верно, но можно просто как минимум посмотреть по каким URL обращается и сразу же заметить, что код ищет html элементы через regex. Так что даже быстрый скролл кода порой может помочь

**Comment by redplcs** [comment]
> > Я не питонист
> 
> Это верно, но можно просто как минимум посмотреть по каким URL обращается и сразу же заметить, что код ищет html элементы через regex. Так что даже быстрый скролл кода порой может помочь

Повторюсь, чем изучать работу кода, даже просто если пробежать, мне проще спросить
